FROM docker.io/golang:1.20.2-bullseye

RUN apt-get update && apt-get install -y alsa-utils libasound2-dev libudev-dev libx11-dev libxcursor-dev libgl-dev libxinerama-dev libxi-dev libxrandr-dev mesa-common-dev libglu1-mesa-dev freeglut3-dev libgl1-mesa-dev xorg-dev

WORKDIR /usr/src/app
