FROM docker.io/arm64v8/golang:1.19.5-bullseye

RUN apt-get update && apt-get install -y libx11-dev libxcursor-dev libgl-dev libxinerama-dev libxi-dev libxrandr-dev mesa-common-dev libglu1-mesa-dev freeglut3-dev libgl1-mesa-dev xorg-dev

WORKDIR /usr/src/app
